---
title: "Andrew Chisholm Referenced Material"
execute:
  freeze: false
  cache: false
format: pdf
keep-tex: false
editor: visual
bibliography: Chichester.bib
params:
  bibliography_file: Chichester.bib
---

<!-- export the bib file from Zotero using Better BibLaTex -->

<!-- and ensure notes are exported -->

```{r}
#| echo: false

# This no longer needed - see the file _quarto.yml
# which contains a pre-render instruction to run
# the file process_bib.R
#suppressWarnings(suppressMessages(source('process_bib.R')))
```

# Referenced Material

## Overview

This is a full list of the items in my Zotero library [@ZoteroYourPersonal2022]. As time permits, I add a short description for each entry.

The links aren't guaranteed to work since they will refer to files in my environment.

In general, if an item is in this list, I will have access to a copy of the source material. Where I refer to an item in a lecture, it should be in this list. If not, let me know. Harvard referencing is used but is not perfect so there may be errors. Again, let me know if there's anything wrong.

A bibliography database file is available on request. This will work with Zotero [@ZoteroYourPersonal2022] as well as Mendeley [@MendeleyReferenceManager2023].

I used \href{http://www.overleaf.com}{Overleaf} [@OverleafOnlineLaTeX2022] to create this document initially. I then migrated to \href{https://quarto.org/}{Quarto} [@Quarto2021].

## Details

{{< include refs.qmd >}}

### References

::: {#refs}
:::
